### ISSUE TITLE
script is not running

### ISSUE THREAD

**Issue by kamleshkumarverma1986** [siddheshshankar/Covid-availability-check#1]
i ran this command: python app.py
getting the below error:

File "app.py", line 30
    def get_centers(read_json, fee_type: str, age_limit: int, start_time: datetime, finish_time: datetime, availability:str):
                                       ^
SyntaxError: invalid syntax

**Comment by siddheshshankar** [comment]
It is working fine for me. Since it is a syntax error, please check if you have given proper indentation.

**Comment by mohitgangwar1** [comment]
It doesn't work for me as well. Not sure where the indentation going wrong. Below is what i get:

-------------------------------------------------------------------------
mohitgangwar@Mohits-Air Covid-Availability-Check-main % python app.py
  File "app.py", line 30
    def get_centers(read_json, fee_type: str, age_limit: int, start_time: datetime, finish_time: datetime, availability: str):
                                       ^
SyntaxError: invalid syntax

**Comment by siddheshshankar** [comment]
@kamleshkumarverma1986 @mohitgangwar1 
Can you try it now. It is working fine for me. 

![image](https://user-images.githubusercontent.com/34763849/117526144-c0f8d480-afe0-11eb-9351-bed8edc6691f.png)

If it still doesn't work, we can probably connect over google meet/zoom to debug the issue.

**Comment by mohitgangwar1** [comment]
It still doesn't work. Let's connect over Zoom. Can you share the invite please?

**Comment by siddheshshankar** [comment]
Please send me your email id. I will mail you the invite.

**Comment by mohitgangwar1** [comment]
its mohitgangwar92@gmail.com

**Comment by siddheshshankar** [comment]
Resolved
